import { fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import AdminTopUpForm from "./AdminTopUpForm";
import AssetCard from "./AssetCard";
import AssetList from "./AssetList";
import BillingSummaryCard from "./BillingSummaryCard";
import CreateProjectForm from "./CreateProjectForm";
import JobDetailPanel from "./JobDetailPanel";
import ProjectJobsPanel from "./ProjectJobsPanel";
import ProjectSelector from "./ProjectSelector";
import QuotaSummaryCard from "./QuotaSummaryCard";
import TransactionHistory from "./TransactionHistory";
import EmptyState from "../ui/EmptyState";
import ErrorBanner from "../ui/ErrorBanner";
import WarningCallout from "../ui/WarningCallout";

test("reusable UX states render accessible content",()=>{render(<><EmptyState title="Nothing here" description="Create something."/><ErrorBanner message="Request failed"/><WarningCallout>Careful</WarningCallout></>);expect(screen.getByText("Nothing here")).toBeVisible();expect(screen.getByRole("alert")).toHaveTextContent("Request failed");expect(screen.getByText("Careful")).toBeVisible();});

test("project selector and create form emit user choices",async()=>{const change=vi.fn(),create=vi.fn();render(<><ProjectSelector projects={[{id:"p",name:"Project"}]} value="" onChange={change}/><CreateProjectForm onSubmit={create}/></>);await userEvent.selectOptions(screen.getByLabelText("Project"),"p");expect(change).toHaveBeenCalledWith("p");await userEvent.type(screen.getByPlaceholderText("New project name"),"New");await userEvent.click(screen.getByRole("button",{name:"Create project"}));expect(create).toHaveBeenCalledWith("New");});
test("billing quota and transactions render summaries",()=>{render(<><BillingSummaryCard billing={{available_credits:90,balance_credits:100,reserved_credits:10,lifetime_used_credits:5}}/><QuotaSummaryCard usage={{daily_jobs:1,monthly_jobs:2}} quotas={{daily_job_limit:10,monthly_job_limit:20,max_concurrent_jobs:3}}/><TransactionHistory transactions={[{id:"t",type:"top_up",amount_credits:100}]}/></>);expect(screen.getByText("90")).toBeVisible();expect(screen.getByText(/100 balance/)).toBeVisible();expect(screen.getByText("1 / 10 daily jobs")).toBeVisible();expect(screen.getByText(/top_up/)).toBeVisible();});
test("asset card renders warning status and direct link",()=>{render(<AssetCard asset={{asset_type:"video",status:"expired",warning:"Expired warning",url:"https://provider.test/v.mp4"}}/>);expect(screen.getByText("expired")).toHaveClass("status-badge","expired");expect(screen.getByText("Expired warning")).toBeVisible();expect(screen.getByRole("link",{name:"Open / Download"})).toHaveAttribute("href","https://provider.test/v.mp4");});
test("job list opens rows and detail renders assets",async()=>{const open=vi.fn();const job={job_id:"j",type:"script.generate",status:"completed",progress_current:1,progress_total:1,attempt_count:1,max_attempts:3,created_at:"2026-06-30T00:00:00Z"};render(<><ProjectJobsPanel jobs={[job]} onOpenJob={open}/><JobDetailPanel job={job} assets={[]}/></>);expect(screen.getAllByText("completed")).toHaveLength(2);expect(screen.getByText("Progress 1/1")).toBeVisible();await userEvent.click(screen.getByRole("button",{name:/script.generate/}));expect(open).toHaveBeenCalledWith("j");expect(screen.getByText("Attempt 1/3")).toBeVisible();});
test("admin top-up submits numeric control",()=>{const submit=vi.fn(event=>event.preventDefault()),change=vi.fn();render(<AdminTopUpForm amount={100} onAmountChange={change} onSubmit={submit}/>);fireEvent.change(screen.getByLabelText("Top-up amount"),{target:{value:"200"}});expect(change).toHaveBeenCalledWith("200");fireEvent.click(screen.getByRole("button",{name:"Admin top-up"}));expect(submit).toHaveBeenCalled();});
test("credit and quota warnings explain constrained projects",()=>{const {rerender}=render(<BillingSummaryCard billing={{available_credits:0,balance_credits:0,reserved_credits:0,lifetime_used_credits:1}}/>);expect(screen.getByText(/no available credits/)).toBeVisible();rerender(<BillingSummaryCard billing={{available_credits:50,balance_credits:50,reserved_credits:0,lifetime_used_credits:1}}/>);expect(screen.getByText(/running low/)).toBeVisible();rerender(<QuotaSummaryCard usage={{daily_jobs:8,monthly_jobs:90}} quotas={{daily_job_limit:10,monthly_job_limit:100,max_concurrent_jobs:3}}/>);expect(screen.getByText(/Daily job quota is almost used/)).toBeVisible();expect(screen.getByText(/Monthly job quota is almost used/)).toBeVisible();});
test("dashboard panels show empty states",()=>{render(<><TransactionHistory transactions={[]}/><ProjectJobsPanel jobs={[]} onOpenJob={()=>{}}/><JobDetailPanel job={null} assets={[]}/><AssetList assets={[]}/></>);expect(screen.getByText("No transactions yet")).toBeVisible();expect(screen.getByText("No project jobs yet")).toBeVisible();expect(screen.getByText("Select a job")).toBeVisible();expect(screen.getByText("No assets yet")).toBeVisible();});
test("asset warnings distinguish expiring and expired",()=>{const {rerender}=render(<AssetCard asset={{asset_type:"video",status:"expiring_soon",url:"https://x"}}/>);expect(screen.getByText(/may expire soon/)).toBeVisible();rerender(<AssetCard asset={{asset_type:"video",status:"expired",url:"https://x"}}/>);expect(screen.getByText(/may have expired/)).toBeVisible();});
test("create and top-up forms disable during submission",()=>{render(<><CreateProjectForm onSubmit={()=>{}} submitting/><AdminTopUpForm amount={10} onAmountChange={()=>{}} onSubmit={()=>{}} submitting/></>);expect(screen.getByRole("button",{name:"Creating…"})).toBeDisabled();expect(screen.getByRole("button",{name:"Topping up…"})).toBeDisabled();});
